export const memesData = [
  {
    success: true,
    data: {
      memes: [
        {
          id: "247375501",
          name: "Buff Doge vs. Cheems",
          url: "https://i.imgflip.com/43a45p.png",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "129242436",
          name: "Change My Mind",
          url: "https://i.imgflip.com/24y43o.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "222403160",
          name: "Bernie I Am Once Again Asking For Your Support",
          url: "https://i.imgflip.com/3oevdk.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "438680",
          name: "Batman Slapping Robin",
          url: "https://i.imgflip.com/9ehk.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "4087833",
          name: "Waiting Skeleton",
          url: "https://i.imgflip.com/2fm6x.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "135256802",
          name: "Epic Handshake",
          url: "https://i.imgflip.com/28j0te.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "97984",
          name: "Disaster Girl",
          url: "https://i.imgflip.com/23ls.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "102156234",
          name: "Mocking Spongebob",
          url: "https://i.imgflip.com/1otk96.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "252600902",
          name: "Always Has Been",
          url: "https://i.imgflip.com/46e43q.png",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "91538330",
          name: "X, X Everywhere",
          url: "https://i.imgflip.com/1ihzfe.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "119139145",
          name: "Blank Nut Button",
          url: "https://i.imgflip.com/1yxkcp.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "100777631",
          name: "Is This A Pigeon",
          url: "https://i.imgflip.com/1o00in.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
        {
          id: "61579",
          name: "One Does Not Simply",
          url: "https://i.imgflip.com/1bij.jpg",
          width: 700,
          height: 700,
          box_count: 2,
        },
      ],
    },
  },
];
